[package]
authors.workspace = true
name = "integration-test"
version.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
av-layer = { workspace = true }
